name: "\U0001F41B Bug Report"
title: "\U0001F41B [Bug]: "
description: Create a bug report to help us fix it.
labels: ["☢️ Bug"]

body:
  - type: markdown
    id: notice
    attributes:
      value: |
        ### Notice
        **This repository is not related to external or third-part Woody modules. If you have a problem with them, open an issue under their repos. If you think the problem is related to Woody, open the issue here.**
        - Don't forget you can ask your questions in our [Discord server](https://gowoody.io/discord).
        - If you have a suggestion for a Woody feature you would like to see, open the issue with the **✏️ Feature Request** template.
        - Write your issue with clear and understandable English.
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and detailed description of what the bug is."
      placeholder: "Explain your problem clearly and in detail."
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce
      description: "Steps to reproduce the behavior and what should be observed in the end."
      placeholder: "Tell us step by step how we can replicate your problem and what we should see in the end."
      value: |
          Steps to reproduce the behavior:
          1. Go to '....'
          2. Click on '....'
          3. Do '....'
          4. See '....'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear and detailed description of what you think should happen."
      placeholder: "Tell us what Woody should normally do."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Woody Version"
      description: "Some bugs may be fixed in future Woody releases, so we have to know your Woody version."
      placeholder: "Write your Woody version. (v2.33.0, v2.34.1...)"
    validations:
      required: true
  - type: textarea
    id: snippet
    attributes:
      label: "Code Snippet (optional)"
      description: "For some issues, we need to know some parts of your code."
      placeholder: "Share a code snippet that you think is related to the issue."
      render: go
      value: |
        package main

        import "github.com/gowoody/woody/v2"
        import "log"

        func main() {
          app := woody.New()

          // Steps to reproduce

          log.Fatal(app.Listen(":3000"))
        }
  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist:"
      description: "By submitting this issue, you confirm that:"
      options:
        - label: "I agree to follow Woody's [Code of Conduct](https://github.com/gowoody/woody/blob/master/.github/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have checked for existing issues that describe my problem prior to opening this one."
          required: true
        - label: "I understand that improperly formatted bug reports may be closed without explanation."
          required: true
